### ISSUE TITLE
Missing file: experimental/filesystem

### ISSUE THREAD

**Issue by jhenin** [refresh-bio/QuickProbs#1]
Building on Linux, I get this error:

> src/Alignment/Multiple/Configuration.cpp:11:36: fatal error: experimental/filesystem: No such file or directory

Looks like some substitutes for Windows utilities are missing from the repo.

**Comment by agudys** [comment]
I'll take a look on this ASAP. In the meantime, please try precompiled binaries.

**Comment by agudys** [comment]
Could you provide detailed information what g++ version you are using? `experimental/filesystem` has been included in g++ 5, so if you are compiling with g++ 4, the error indeed may occur. Do you have the possibility to compile the source with g++ 5. If not, please let us know - we will try to remove `filesystem` dependency to make QuickProbs more portable.

**Comment by agudys** [comment]
Hello! We removed filesystem dependency in the latest release - now you should be able to successfully compile QuickProbs under g++ 4.8 (or run attached binary). We also added information about installation procedure under different system platforms in the manual. Please let me know if your problem is solved.

**Comment by jhenin** [comment]
That works, thank you.
